[tools]
node = '24.4'
pnpm = '10'  # 実際に使うバージョンは package.json の packageManager で指定。 pnpm v10 から manage-package-manager-versions=true がデフォルトで有効。

'aqua:BurntSushi/ripgrep' = 'latest'
task = 'latest' # タスクランナー

[settings]
pipx.uvx = true # tools の 'pip:*' を pipx ではなく uvx でインストールする

[settings.status]
missing_tools = 'always'
show_env = true
