version: '3'

includes:
  podman:
    taskfile: Taskfile.container.yaml
    vars:
      DOCKER: podman
  docker:
    taskfile: Taskfile.container.yaml
    vars:
      DOCKER: docker

tasks:
  install:
    desc: Install dependencies
    cmd: pnpm i

  test-files:copy:
    desc: Copy each test files 10 times (For emulating multiple test files)
    cmd: ./scripts/copy-test-files.ts copy ./src/infrastructure/postgres/__test__ 10

  test-files:remove:
    desc: Remove copied test files
    cmd: ./scripts/copy-test-files.ts remove ./src/infrastructure/postgres/__test__

  db:migrate:status:
    desc: Show migration status
    cmd: pnpm prisma migrate status

  db:migrate:deploy:
    desc: Deploy migration scripts
    cmd: pnpm prisma migrate deploy

  db:migrate:gen:
    desc: Generate migrations
    cmd: pnpm prisma migrate dev --create-only

  db:gen:
    desc: Generate Prisma client
    cmd: pnpm prisma generate
